### PR TITLE
Implement a generic .detached_log_prob() method

### PR DESCRIPTION
**Pull request by fritzo**
Resolves https://github.com/pytorch/pytorch/issues/25783

This attempts to implement a `.detached_log_prob()` method using the machinery of `.expand()`.

## Tasks
- [ ] add tests

### CODE REVIEW

**Comment by iffsid** [comment]
Thanks for this!
Testing out the changes; Fighting with getting pytorch to compile from source on my machine. :slightly_smiling_face: 
Are there any caveats I should be aware of when compiling? Any flags or settings I should be aware of that let me test this out without too much fuss? Or should I just bite the bullet and get things to compile?

**Comment by fritzo** [comment]
@iffsid Re compiling, the [docs](https://github.com/pytorch/pytorch/#from-source) usually work for me.

If you just want to hack and you don't need the fixes to `MultivariateNormal` and `LowRankMultivariateNormal` you can monkey patch PyTorch by pasting something like this in your code (voiding warrantees):
```py
import torch

def detached_log_prob(self, value):
    batch_dim = 1 + max(len(self.batch_shape), value.dim() - len(self.event_shape))
    detached_shape = (1,) * (batch_dim - len(self.batch_shape)) + self.batch_shape
    with torch.no_grad():
        detached = self.expand(detached_shape)
    return detached.log_prob(value)[0]

torch.distributions.Distribution.detached_log_prob = detached_log_prob
```

**Comment by iffsid** [comment]
Cool, yes. I couldn't get pytorch to compile---some stuff about caffe, but yes, testing with a monkey patch on my simple mnist setup. :+1:

**Comment by iffsid** [comment]
Ok, a minimal check seems to be breaking---unsure if because of monkey patch.
``` python
import torch
import torch.nn as nn
import torch.distributions as dist

TEST_NEW_LP = True

def detached_log_prob(self, value):
    batch_dim = 1 + max(len(self.batch_shape), value.dim() - len(self.event_shape))
    detached_shape = (1,) * (batch_dim - len(self.batch_shape)) + self.batch_shape
    with torch.no_grad():
        detached = self.expand(detached_shape)
    return detached.log_prob(value)[0]

torch.distributions.Distribution.detached_log_prob = detached_log_prob

params = nn.Parameter(torch.zeros(3,4)), nn.Parameter(torch.ones(3,4))
d = dist.Normal(*params)
z = d.rsample(torch.Size([3]))

if TEST_NEW_LP:
    log_d = d.detached_log_prob(z).sum()
else:
    log_d = d.__class__(d.loc.detach(), d.scale.detach()).log_prob(z).sum()

loss = -log_d
loss.backward()
```

Running the above (as `/tmp/foo.py`) with `TEST_NEW_LP=False` works fine, but with `TEST_NEW_LP=True`, causes the following error:
```
Traceback (most recent call last):
  File "/tmp/foo.py", line 26, in <module>
    loss.backward()
  File "/home/<...>/.virtualenvs/default/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/<...>/.virtualenvs/default/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: No grad accumulator for a saved leaf!
```

If I try and instrument the `detached_log_prob` to check the value of `requires_grad`, it appears that the detach doesn't happen:
```python
import torch
import torch.nn as nn
import torch.distributions as dist

TEST_NEW_LP = True

def detached_log_prob(self, value):
    batch_dim = 1 + max(len(self.batch_shape), value.dim() - len(self.event_shape))
    detached_shape = (1,) * (batch_dim - len(self.batch_shape)) + self.batch_shape
    with torch.no_grad():
        detached = self.expand(detached_shape)
    print("self:", self.loc.requires_grad, self.scale.requires_grad)
    print("detached:", detached.loc.requires_grad, detached.scale.requires_grad)
    return detached.log_prob(value)[0]

torch.distributions.Distribution.detached_log_prob = detached_log_prob

params = nn.Parameter(torch.zeros(3,4)), nn.Parameter(torch.ones(3,4))
d = dist.Normal(*params)
z = d.rsample(torch.Size([3]))

if TEST_NEW_LP:
    log_d = d.detached_log_prob(z).sum()
else:
    log_d = d.__class__(d.loc.detach(), d.scale.detach()).log_prob(z).sum()

loss = -log_d
loss.backward()
```
giving as output
```
self: True True
detached: True True
Traceback (most recent call last):
  File "/tmp/foo.py", line 28, in <module>
    loss.backward()
  File "/home/nsid/.virtualenvs/default/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/nsid/.virtualenvs/default/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: No grad accumulator for a saved leaf!
```

**Comment by neerajprad** [comment]
This is a clever way to address the issue! 

My only question is regarding the interface - this seems like the kind of method that probably belongs in Pyro's `TorchDistributionMixin`. WDYT? If we put this in `torch.distributions`, it might be worth putting in the work to have a more general `.detach` method that returns a detached copy of the distribution, though that will also require some way to access all distribution parameters as you said, and the `.expand `trick won't work there.

**Comment by fritzo** [comment]
Oh no, this won't work because `.expand()` does not respect `torch.no_grad()` 😞 Sorry @iffsid I'm really surprised, and this seems like a PyTorch bug to me.
```py
x = torch.tensor(0., requires_grad=True)
with torch.no_grad():
    y = x.expand(1)
y.requires_grad
## True
```

**Comment by iffsid** [comment]
@fritzo No worries! :slightly_smiling_face: 
I was puzzled with that too, but didn't know if I should view this as a pytorch issue because I didn't quite know what the semantics of `torch.no_grad` were supposed to be!

**Comment by fritzo** [comment]
We can reopen this once https://github.com/pytorch/pytorch/issues/25932 is fixed.

**Pull request closed without merging**
